init:
	poetry config virtualenvs.in-project true
	poetry install

local:
	cd src; litestar run --debug

format:
	@poetry run black alembic src test
	@poetry run isort alembic src test

check:
	@poetry run black alembic src test --check
	@poetry run isort alembic src test --check
	@poetry run ruff check src test

db-generate COMMENT:
	alembic revision --autogenerate -m "{{COMMENT}}" 

db-downgrade:
	alembic downgrade -1

db-upgrade:
	alembic upgrade +1

db-upgrade-all:
	alembic upgrade head

db-fill:
	@poetry run python script/1.populate_database.py

db-reset: db-downgrade db-upgrade db-fill

migration-generate VERSION_FROM VERSION_TO:
	@poetry run python script/8.generate_sprite_pack_migration.py {{VERSION_FROM}} {{VERSION_TO}}

migration-apply VERSION_FROM VERSION_TO:
	@poetry run python script/9.apply_sprite_pack_migration.py {{VERSION_FROM}} {{VERSION_TO}}
